// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0V2QgyL4tNExfIl-JNjBRMh1Mz_54yQ',
    appId: '1:762624889418:web:e544d5f3ec1c9bf4064cb3',
    messagingSenderId: '762624889418',
    projectId: 'flutterfire-7a6dc',
    authDomain: 'flutterfire-7a6dc.firebaseapp.com',
    storageBucket: 'flutterfire-7a6dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCah5F5qPH3kntrdt5ZzhbLFe9oRO5F-aI',
    appId: '1:762624889418:android:d62108e0c3f72a8d064cb3',
    messagingSenderId: '762624889418',
    projectId: 'flutterfire-7a6dc',
    storageBucket: 'flutterfire-7a6dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhtncUVPAktxGKxfHgE5nn0HF6lobAJHU',
    appId: '1:762624889418:ios:3bb4a7117dcb679d064cb3',
    messagingSenderId: '762624889418',
    projectId: 'flutterfire-7a6dc',
    storageBucket: 'flutterfire-7a6dc.appspot.com',
    iosClientId: '762624889418-c89r7jkuu4k6j627fjjel3q1n0qt54ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhtncUVPAktxGKxfHgE5nn0HF6lobAJHU',
    appId: '1:762624889418:ios:3bb4a7117dcb679d064cb3',
    messagingSenderId: '762624889418',
    projectId: 'flutterfire-7a6dc',
    storageBucket: 'flutterfire-7a6dc.appspot.com',
    iosClientId: '762624889418-c89r7jkuu4k6j627fjjel3q1n0qt54ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFire',
  );
}
